---
abstract: 'Antibiotic resistome gene database'
author:
  - 'Andrew J. Page <ap13@sanger.ac.uk>'
build_requires:
  Data::Dumper: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Resistome
requires:
  Exception::Class: 0
  Getopt::Long: 0
  LWP::UserAgent: 0
  Moose: 0
  Text::CSV: 0
  URI::Escape: 0
  XML::TreePP: 0
resources:
  homepage: http://www.sanger.ac.uk/
  repository: https://github.com/sanger-pathogens/Bio-Resistome.git
version: 1.123560
